### ISSUE TITLE
Introduce new `entityPrimaryKeyNatural` ordering constraint

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB-C-Sharp-client#2]
See issue: https://github.com/FgForrest/evitaDB/issues/218

Specifially commit: https://github.com/FgForrest/evitaDB/commit/9e65a86cd8d5e013d96d107efde053b73d25240c

Also new support for running documentation tests against localhost server instance was introduced, but I wasn't able to propagate the behaviour to `io.evitadb.documentation.csharp.CsharpTestContext`. Can you consider what to do about it - see other implementations here: `io.evitadb.documentation.evitaql.EvitaTestContext` or here `io.evitadb.documentation.graphql.GraphQLTestContext`

**Comment by Khertys** [comment]
Resolved in: https://github.com/FgForrest/evitaDB-C-Sharp-client/commit/0d8b9fe91f8b3de59dd880bfc4d165591ffb70c6
